### ISSUE TITLE
Backslashes should be escaped in YAML strings.

### ISSUE THREAD

**Issue by jeberger** [js-reporters/js-reporters#114]
If an error message contains backslashes, YAML output looks like this:

```yaml
  ---
  message: "Test failed\"
  severity: failed
  ...
```

which is not valid since the backslash now looks like it's escaping the closing double quote. Instead it should be:

```yaml
  ---
  message: "Test failed\\"
  severity: failed
  ...
```
